---
name: Lógica Digital
locale: es
type: practice
beta: false
teacher_info: ''
language: text
id_format: '%05d'
order:
- 16
- 1
- 2
- 3
- 4
- 5
- 7
- 6
- 8
- 9
- 10
- 11
- 13
- 17
- 12
- 14
- 15
- 19
- 18
- 20
